### ISSUE TITLE
Can this be simpler (esp. use local AuthN instead of github)?

### ISSUE THREAD

**Issue by olyerickson** [jupyterhub/jupyterhub-deploy-teaching#24]
Thanks for this resource!

What would a variant of this procedure look like, that uses local (PAM?) AuthN rather than github? Or, is using github actually easier? 

I currently have a vserver set up for classes on which I'm running RStudio Server. Works nicely, but not as flexible as I'd like and obviously not Jupyter. I'd like to extend our offerings on that server rather than start new.

**Comment by minrk** [comment]
You could use PAM. To do this, you would change the Authenticator config to leave the default instead of selecting GitHubOAuthenticator. What makes using PAM typically more complicated for a class is that you would need to create and distribute usernames and passwords for all of your students, unless PAM on your server is already hooked up to a campus auth system.

**Comment by willingc** [comment]
@olyerickson I'm going to close as resolved based on Min's response. Thanks. Please feel free to ask more questions if needed and I would be happy to reopen :sunny:
